folio-org/ui-ldp

package.json
These changes were requested by @a-mbreaux as part of a review of UI permission names.
=> Clarify UI permission names

CHANGELOG.md, package.json
=> Add low-level "ldp.read" permission to high-level "LDP: all permissions"

CHANGELOG.md, package.json, src/settings/DatabaseConfig.js, src/settings/index.js, translations/ui-ldp/en.json
=> Settings page for database connection configuration

CHANGELOG.md, src/components/QueryBuilder/OrderingCriterion.js
=> Fix translation tags used for aria-labels when choosing sorting criteria

CHANGELOG.md, src/util/loadData.js, translations/ui-ldp/en.json, translations/ui-ldp/en_US.json
=> Better error-reporting for when the LDP database is unavailable

CHANGELOG.md, src/components/QueryBuilder/ResultsList.js
=> Show null values as `[NULL]` in grey

CHANGELOG.md, package.json, src/settings/index.js
=> Complete revamp of permissions

CHANGELOG.md, src/components/QueryBuilder/ColumnFilter.js
=> Allow user to specify operation in column filters

CHANGELOG.md, src/routes/QueryBuilderRoute.js
=> Clear button in query-builder now works consistently

CHANGELOG.md, package.json
=> Fix typo in permission name.

CHANGELOG.md, src/components/QueryBuilder/QuerySingleTable.js
=> The Clear button now consistently disables Submit

CHANGELOG.md, package.json
=> Promote `core-js` to full dependency

package.json
At present, just
* settings.global.read.ui-ldp.admin
* settings.global.write.ui-ldp.admin
=> Add scoped settings permissions

CHANGELOG.md, package.json, src/components/QueryBuilder/SaveQueryModal.js, src/components/SavedQueries/ListSavedQueries.js, src/components/SavedQueries/SavedQueries.js, src/routes/SavedQueriesRoute.js, src/settings/RecordLimits.js, src/settings/TableAvailability.js, src/stripes-smart-components/index.js, src/stripes-smart-components/lib/ConfigManager/ConfigFinalForm.js, src/stripes-smart-components/lib/ConfigManager/ConfigForm.js, src/stripes-smart-components/lib/ConfigManager/ConfigManager.css, src/stripes-smart-components/lib/ConfigManager/ConfigManager.js, src/stripes-smart-components/lib/ConfigManager/ConfigReduxForm.js, src/stripes-smart-components/lib/ConfigManager/index.js, src/stripes-smart-components/lib/ConfigManager/readme.md, src/util/loadConfig.js, translations/ui-ldp/en.json
Includes:
* Update Record Limits/Table Availability to use mod-settings. Fixes UILDP-81.
* Modify JSON query saving/loading to use FOLIO storage (mod-settings). Fixes UILDP-57.
* Newly saved queries now appear on the Saved Query list immediately. Fixes UILDP-41.
Fixes UILDP-78.
=> Port to mod-settings

CHANGELOG.md, src/components/QueryBuilder/SaveQueryModal.js
=> Fix "Validation error for body application/json"

CHANGELOG.md, src/components/QueryBuilder/SaveQueryModal.js
=> Fix "Could not save query [...]: error (): Forbidden".

CHANGELOG.md, src/components/QueryBuilder/SaveQueryModal.js
=> After saving a query, re-saving the same query no longer creates a duplicate

CHANGELOG.md, src/components/QueryBuilder/SaveQueryModal.js, translations/ui-ldp/en.json
=> Handle disappearing queries more gracefully

CHANGELOG.md, src/components/TemplatedQuery/TemplatedQuery.css, src/components/TemplatedQuery/TemplatedQuery.js
=> Download results of running a query as CSV

CHANGELOG.md, src/util/loadResults.js, src/util/loadTables.js
=> Port ui-ldp to work with MetaDB as well as LDP Classic

CHANGELOG.md, package.json
=> Make internal permissions used by mod-settings invisible

CHANGELOG.md, doc/reports.md, src/components/TemplatedQuery/TemplatedQueryForm.js
=> Report metadata files can specify default values for report parameters

CHANGELOG.md, src/components/QueryBuilder/QuerySingleTable.js
=> List of available schemas in query-builder is now sorted

package.json, src/util/fetchTemplatedQueries.js, src/util/gitHubFetch.js, src/util/stripesFetch.js
Also upgrade some dependencies' patch-levels.
Hopefully fixes UILDP-145.
=> Remove cross-fetch polyfill

CHANGELOG.md, src/components/TemplatedQuery/TemplatedQueryForm.js
=> Temporarily use textbox instead of `<AutoSuggest>` in forms.

src/Tabs.js, src/components/Info/Logs.js, src/components/Info/Processes.js, src/index.js, translations/ui-ldp/en.json
* Clicking Database Info goes initially to Updates tab
* Reorder tabs to Updates, Processes, Logs
* Logs displays a spinner while loading the MCL
* Processes displays a more specific message when empty
Part of UILDP-148
=> Tweaks to Database Info section

CHANGELOG.md
=> Pointless change of wording in changelog

CHANGELOG.md, src/components/TemplatedQueries/TemplatedQueries.js, src/util/fetchTemplatedQueries.js
=> Stored reports with no display-name no longer cause a crash
