folio-org/ui-ldp

CHANGELOG.md
package.json

Update dev-deps for compatibility with `@folio/stripes` `^6.0.0` and
remove unused/incompatible deps.
Refs #29

use stripes v6 compatible libraries

---

CHANGELOG.md
README.md

The [`README.md`](../blob/master/README.md) file has been updated accordingly.
Fixes UILDP-9.

Move from `library-data-platform` to `folio-org` complete

---

CHANGELOG.md
src/components/QueryBuilder/QueryBuilder.js

If any schema-names loaded into the form from the previous session's
state refer to schemas no longer supported by the back-end database,
they are now changed to refer to a valid schema instead.
Fixes UILDP-48.

Ensure schema names from saved form state are valid

---

src/util/gitHubFetch.js

Chrome refuses to accept this for security reasons, and it doesn't
seem to be necessary anyway.

Remove setting of User-Agent header

---

CHANGELOG.md
src/components/QueryBuilder/QueryBuilder.js
src/components/QueryBuilder/SaveQueryModal.js

When the save-query modal popus up, the display-name field is
autofocused. As the user types into it, it is copied into the filename
field, with all letters downcased and all non-alphanumerics replaced
by underscored.
Once the user manually edits the filename, the copying no longer
happens. So you can type a display-name, get an autogenerated
filename, tweak that filename to your preference, then change the
display-name wihtout losing your filename changes.
Fixes UILDP-46.

Save query: filename is auto-generated from the display-name

---

package.json
src/settings/SavedQueriesConfig.js
src/settings/components/LdpConfig.js

This allows us to avoid displaying the GitHub token that mod-ldp has
stored and returned to us, while still allowing it to be edited. To
the user, the result is as with the DB Config page's password, but
unlike that password we do need the server to actually give the client
the GitHub token, otherwise we can't use saved searches.

Fake read-only status for GitHub token

---

CHANGELOG.md
package.json
src/index.js

`core-js` no longer listed as a dependency at all

---

CHANGELOG.md
src/settings/TableAvailability.js

"Table availability" list  is now sorted correctly

---

package.json

Previously, they included as subpermissions low-level permissions from mod-configuration, which we no longer use. Noe they include the relevant low-level permissions from mod-settings, as well as the appropriate scope-specific settings permissions provided by this module.
We still need to think about how to deal with permission to save queries.

Rework high-level permissions to work with mod-settings

---

CHANGELOG.md
src/components/QueryBuilder/QueryBuilder.js
src/util/loadResults.js

Previously, large sets were limited to mod-ldp's default of 500.
Fixes UILDP-68.

Record export limit now applies to large sets

---

CHANGELOG.md
package.json

(Though this should still work with v6 and v7).
For subtle reasons, to with `rxjs` versions, to get this to work it was necessary to downgrade Cypress from `^7.4.0` to `^6.4.0`. This will do for now, but as Cypress has leapt ahead five more major versions to v12.5.1 at the time of writing, we will clearly need to revisit this.
Fixes UILDP-79.

Upgrade from Stripes v7 to Stripes v8

---

CHANGELOG.md

Turns out this was fixed back in v1.9.0.

Change-logging (belatedly) for UILDP-76

---

CHANGELOG.md
src/components/TemplatedQueries/TemplatedQueries.js
src/components/TemplatedQuery/TemplatedQuery.js
src/components/TemplatedQuery/index.js
src/index.js
src/routes/TemplatedQueryRoute.js
src/util/defaultConfig.js
src/util/templatedQueryName.js
translations/ui-ldp/en.json

At this point, the tabs only show a JSON rendering of the query and associated metdata. We'll address that in UILDP-104.
Fixes UILDP-99.

Create dynamic tabs for selected Templated Queries

---

CHANGELOG.md
src/components/TemplatedQuery/TemplatedQuery.js
src/util/loadReport.js

The number of records retrieved for templated queries is limited according to the configured `maxShow` parameter.
Fixes UILDP-112.

Limit number of records retrieved for reports

---

CHANGELOG.md
src/components/QueryBuilder/QueryBuilder.css
src/components/QueryBuilder/QueryBuilder.js
src/components/QueryBuilder/QuerySingleTable.js
src/components/QueryBuilder/ResultsList.js

Results from query-builder appear in place of, rather than below, the query for.
Fixes UILDP-118, though we will revisit this UX in a future release.

Query-builder results pop up over query

---

CHANGELOG.md
src/components/QueryBuilder/QueryBuilder.js
src/util/localforage-with-logging.js

Submitting a query from the builder, then closing the results, no longer resets to the last loaded query.
I have _absolutely no idea_ why this fixes fixes this bug, but it does. And since I still have absolutely no idea how the bug happens in the first place, I guess it all balances out.
¯\_(ツ)_/¯
Fixes UILDP-130.

Closing results no longer resets query to last loaded

---

CHANGELOG.md
src/components/QueryBuilder/QuerySingleTable.js

When there are no tables in the selected schema (e.g. because a back-end problems reports no tables at all), the UI is now robust against this condition.
Fixes UILDP-151.

Do not crash if back-end reports no tables available

---

CHANGELOG.md
src/components/SavedQueries/ListSavedQueries.js

Queries that have been saved for the first time no longer show "Invalid date" in the Date Last Updated field in the Load Query list.
Fixes UILDP-152.

Fix "Invalid date" message in "Load query" list.

---

CHANGELOG.md
src/components/TemplatedQuery/TemplatedQueryForm.js

It seems the fix for the underlying `<AutoSuggest>` field in stripes-components has become available, so it's a simple matter of reinstating the commented-out code.
Fixes UILDP-110.

Support `<AutoSuggest>` parameters in templated queries

---

CHANGELOG.md
src/util/repoTypes.js

Report-repository configuration now allows directory to be left blank (or specified as `/`) to indicate the top level of the repository.
Fixes UILDP-156.

Allow report repository directory to be left empty

---

CHANGELOG.md
src/components/QueryBuilder/ResultsList.js

Use `exportToCsv` from `stripes-components` instead of a deprecated `exportCsv` from `stripes-utils`
[UILDP-150](https://folio-org.atlassian.net/browse/UILDP-150)

UILDP-150 Change import of `exportToCsv` from `stripes-util` to `stripes-components`

---

CHANGELOG.md
package.json
src/routes/TemplatedQueriesRoute.js
src/util/fetchTemplatedQueries.js

While loading the list of reports, display a spinner instead of a premature empty-list message.

[UILDP-173] Show spinner while loading reports

---

CHANGELOG.md
package.json
src/stripes-components/lib/ExportCsv/exportToExcel.js

Switch from the `xslt` dependency, which while maintained is no longer published to NPM, to the mirror version `@e965/xslt`. This fixes two known security issues.

[UILDP-175] Switch to `@e965/xslt` for security patches

---

CHANGELOG.md
src/util/fetchTemplatedQueries.js

When failing to parse a malformed report-metadata JSON file, the error message displayed to the user now includes the path to the faulty file, so it can be fixed or removed.

[UILDP-176] JSON-parse error messages include file URL
